### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by manishvel8** [Interbotix/interbotix_ros_manipulators#135] opened 2023-11-06 10:50 UTC
### Question

Hi Team,
Is the Interbotix WX 200 robotic arm able to play chess?

### Robot Model

wx200

### Operating System

Ubuntu 20.04

### ROS Version

ROS 1 Noetic

**Comment by LSinterbotix** [comment] 2023-11-06 17:19
Duplicate of #136.

**Closed by LSinterbotix** 2023-11-06 17:19 UTC
Labels: question, manipulators
